compressionLevel: mixed
enableGlobalCache: false
nodeLinker: node-modules
injectEnvironmentFiles: [
  ".env",
]
npmScopes: {
  arthurhovhannisyan31: {
    npmRegistryServer: "https://npm.pkg.github.com",
    npmAuthToken: "${NODE_AUTH_TOKEN-}",
    npmAlwaysAuth: true
  }
}
