compressionLevel: mixed
enableGlobalCache: false
nodeLinker: node-modules
injectEnvironmentFiles:
  - .env?
npmScopes:
  arthurhovhannisyan31:
    npmAlwaysAuth: true
    npmAuthToken: "${NODE_AUTH_TOKEN-}"
    npmRegistryServer: "https://npm.pkg.github.com"
